#!/usr/bin/env node
// Bundles everything the CMS (/admin) edits — the JSON files in /content — into one
// file, content.generated.js, which data.js, info-content.js, gallery.jsx and
// our-story.jsx read. Runs automatically on every Vercel deploy (see vercel.json);
// run it yourself with `npm run build:content` after editing /content by hand.
const fs = require("fs");
const path = require("path");
const root = path.join(__dirname, "..");
const content = path.join(root, "content");

const read = (rel) => {
  try {
    return JSON.parse(fs.readFileSync(path.join(content, rel), "utf8"));
  } catch (e) {
    console.error(`✗ content/${rel}: ${e.message}`);
    process.exit(1);
  }
};
const readDir = (dir) =>
  fs.readdirSync(path.join(content, dir)).filter(f => f.endsWith(".json")).sort()
    .map(f => ({ file: f.replace(/\.json$/, ""), data: read(`${dir}/${f}`) }));

const out = {
  store: read("store.json"),
  home: read("home.json"),
  gallery: read("gallery.json"),
  story: read("story.json"),
  products: readDir("products").map(x => x.data),
  pages: Object.fromEntries(readDir("pages").map(x => [x.file, x.data])),
};

const js = `/* AUTO-GENERATED by \`npm run build:content\` from /content — do not edit by hand. */\n` +
  `(function(){var C=${JSON.stringify(out, null, 1)};\n` +
  `if(typeof module!=="undefined"&&module.exports)module.exports=C;else window.IL_MANO_CONTENT=C;})();\n`;
fs.writeFileSync(path.join(root, "content.generated.js"), js);
console.log(`✓ content.generated.js — ${out.products.length} products, ${Object.keys(out.pages).length} pages`);
