#!/usr/bin/env node
// Makes small copies of every photo in /assets so phones don't download desktop-size files.
//   npm run images
// For assets/foo.webp it writes assets/opt/foo-480.webp, -900.webp, -1400.webp (never larger than
// the original) and records them in assets/opt/manifest.js, which the site reads automatically.
// Keep the originals — they stay the "master" copies. Safe to re-run; unchanged files are skipped.
const fs = require("fs");
const path = require("path");
const sharp = require("sharp");

const root = path.join(__dirname, "..");
const assets = path.join(root, "assets");
const out = path.join(assets, "opt");
const WIDTHS = [480, 900, 1400];
const QUALITY = 78;
const EXT = /\.(jpe?g|png|webp)$/i;

function walk(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap(e => {
    const p = path.join(dir, e.name);
    if (p === out) return [];
    return e.isDirectory() ? walk(p) : EXT.test(e.name) ? [p] : [];
  });
}

(async () => {
  const manifest = {};
  let made = 0;
  for (const file of walk(assets).sort()) {
    const rel = path.relative(root, file).split(path.sep).join("/");           // assets/hoodie.webp
    const stem = path.relative(assets, file).replace(EXT, "").split(path.sep).join("/");
    const meta = await sharp(file).metadata();
    const widths = WIDTHS.filter(w => w < meta.width);
    if (!widths.length || widths[widths.length - 1] < meta.width) widths.push(meta.width <= WIDTHS[WIDTHS.length - 1] ? meta.width : WIDTHS[WIDTHS.length - 1]);
    manifest[rel] = { stem, widths: [...new Set(widths)].sort((a, b) => a - b) };
    for (const w of manifest[rel].widths) {
      const dest = path.join(out, `${stem}-${w}.webp`);
      if (fs.existsSync(dest) && fs.statSync(dest).mtimeMs >= fs.statSync(file).mtimeMs) continue;
      fs.mkdirSync(path.dirname(dest), { recursive: true });
      await sharp(file).resize({ width: w, withoutEnlargement: true }).webp({ quality: QUALITY }).toFile(dest);
      made++;
    }
  }
  const js = `/* AUTO-GENERATED by \`npm run images\` — do not edit. */\n(function(){var M=${JSON.stringify(manifest, null, 1)};\nif(typeof module!=="undefined"&&module.exports)module.exports=M;else window.IL_MANO_IMAGES=M;})();\n`;
  fs.mkdirSync(out, { recursive: true });
  fs.writeFileSync(path.join(out, "manifest.js"), js);
  console.log(`✓ ${Object.keys(manifest).length} photos indexed, ${made} new resized file(s) written to assets/opt/`);
})();
